language: java
jdk:
  - oraclejdk11
  - oraclejdk13
  - openjdk11
  - openjdk13
  - openjdk14

after_success:
  - |
    if [ "${JAVA_HOME}" = "/home/travis/openjdk12" ]; then
      mvn jacoco:report coveralls:report
    fi